// app/layout.tsx
import type { Metadata } from "next";
import "../styles/globals.css";
import Navbar from "../component/Navbar";
import Footer from "../component/Footer";
import Script from "next/script";
import { AuthProvider } from "../app/context/auth-context";
import ChatbotWrapper from "../component/ChatbotWrapper";
import CurhatWrapper from "../component/CurhatWrapper";

// Gunakan next/font/google (rekomendasi Next.js)
import { Roboto_Mono } from "next/font/google";
import { Grandstander } from "next/font/google";

// Import untuk Geist sudah bagus, tidak perlu diubah
import { Geist, Geist_Mono } from "next/font/google";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const robotoMono = Roboto_Mono({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-roboto-mono",
});

const grandstander = Grandstander({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-grandstander",
});

export const metadata: Metadata = {
  title: "Look My Education",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" suppressHydrationWarning >
      <head>
        {/* Material Icons masih perlu pakai <link>, aman */}
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@48,400,1,0&display=optional"
        />
        <Script
          src="https://cdn.jsdelivr.net/npm/emoji-mart@latest/dist/browser.js"
          strategy="afterInteractive"
        />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${robotoMono.variable} ${grandstander.variable} antialiased`}
      >
          <AuthProvider>
            <Navbar />
            <ChatbotWrapper />
            {children}
            <CurhatWrapper />
            <Footer />
          </AuthProvider>
      </body>
    </html>
  );
}
